### ISSUE TITLE
Generic architectural prototype for snet services

### ISSUE THREAD

**Issue by andre-senna** [singnet/dnn-model-services#1]
Moved to [example-service](https://github.com/singnet/example-service).

**Comment by arturgontijo** [comment]
Local tests are running as expected.
Waiting for final release of CLI and dApp with gRPC integrated to test it on the blockchain.
(CLI and dApp with gRPC release date: 8/20 - 8/24)

**Comment by arturgontijo** [comment]
The new version of CLI was released but not the new dApp.
Preparing the new docs about how to interact with the CLI.

**Comment by arturgontijo** [comment]
See [example-service](https://github.com/singnet/example-service).
