### ISSUE TITLE
Integrating a Meta Service.

### ISSUE THREAD

**Issue by arturgontijo** [singnet/dnn-model-services#13]
Creating a new Service that uses the ObjectDetection Service with the ImageRecon Service to deliver a more complete image analysis.

[Feb] Needs new Daemon mesh arch.

**Comment by arturgontijo** [comment]
Trying to figure out a way to charge the user only for the Meta Service and use this initial fee to call for all other services.

Right now the user pays for Meta and then for each service separately (the user identity has to be sent from Meta to all services).

**Comment by pennachin** [comment]
This isn't explicitly supported, but you can ask Tesfa and Joel on slack if there's a better way (Tesfa wrote a service that calls Joel's face services)

**Comment by arturgontijo** [comment]
I just found something that may cause some pain for us with gRPC.
Unfortunately gRPC doesn't support fork() neither Popen() after a connection is made.
[#15334](https://github.com/grpc/grpc/issues/15334)
[#13873](https://github.com/grpc/grpc/issues/13873#issuecomment-358476408)

If I try to use them inside my service's gRPC server, it trows an:
`154 tcp_server_posix.cc:210]    Failed accept4: Invalid argument`

I'm working on a service that calls another service (it must be able to call `snet client call ...`).
My "for now" solution is to use subprocess.run() instead.

**Comment by arturgontijo** [comment]
Now gRPC supports client side `fork()`.
[Releases](https://github.com/grpc/grpc/releases)

Maybe the server side (our "service side") will be released soon.

PR with MetaService Implementation and Tutorial: #14
