### ISSUE TITLE
Error CNTK Image Recognition Agent - possibly related to the use of non HTTPS addresses

### ISSUE THREAD

**Issue by prashantramangupta** [singnet/dnn-model-services#48]
Description from "'Koen' via Bugs & Issues" <bugs.beta@singularitynet.io>: <br/>Error CNTK Image Recognition Agent - possibly related to the use of non HTTPS addresses<br/><br/>Steps to reproduce:<br/>Use [https://beta.singularitynet.io](https://beta.singularitynet.io/SampleServices)<br/>Start a job on CNTK Image Recognition<br/>Reserve funds / Invoke the job.<br/>Any url image link will give the same result.<br/><br/>EXPECTED RESULT:<br/>To Reproduce use:<br/>[http://beta.singularitynet.io](http://beta.singularitynet.io/SampleServices) instead of the HTTPS<br/>1. Name of fields and their values are located on the same level<br/><br/>ACTUAL RESULT: on HTTPS<br/><br/>Friendly greetings,<br/>Koen

**Comment by arturgontijo** [comment]
This `requestObject` seems to be the outdated one, it's using `imgPath` and not the `img_path`.
If user can provide the image URLs I can test them and check the result.
