### ISSUE TITLE
All video URL's returns fail response

### ISSUE THREAD

**Issue by dan1-ru** [singnet/dnn-model-services#57]
##### **Brief description**
I try to use this service through beta.singularitynet.io
With this videos: 
https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi
http://crcv.ucf.edu/THUMOS14/UCF101/UCF101/v_CricketShot_g04_c02.avi (from User's guide)

And model 400. 

##### **Output logs**

![screenshot from 2019-03-07 12-39-15](https://user-images.githubusercontent.com/7466036/53940356-4a49af00-40d7-11e9-8463-c17ed057bdbb.png)
In both cases service returns:
Status: Ok
Top Predicted Actions:
Fail

##### **Suggest a Fix**

Add video body size limit please, because I was waiting about 10 minutes to get an response (Big buck bunny video).

##### **Browsers and Operating System**
 Ubuntu 16.04, Chromium

**Comment by arturgontijo** [comment]
Hi, @dan1-ru!

The first video has 210Mb and it's (for sure) a big video to be feeded to the I3D model. I think a good solution will be returning the Action Description only for the first seconds (like 10s) and a better error massage, like "The input video was too long, please send it in parts of 10 seconds."
What do you think?

The second video URL seems to be offline here.

**Comment by dan1-ru** [comment]
Yes, I agree with you. Perhaps it is worth hinting to the user that the video should be sliced into chunks before uploading. Also to use not only the number of seconds of the video, but also the size, because  someone to try upload blue-ray video))

Second video downloading today but I didn't playing it (( Probably it has already gone. Sry..

I found cool suitable video here:
https://www.videvo.net/videvo_files/converted/2016_04/videos/160330_1_Typing1_Mpeg4_4K.mov32174.mp4
In this site a lot of good small free videos for testing.
Prediction works perfect! Good for new video example ))
![image](https://user-images.githubusercontent.com/7466036/53986173-494c6800-413f-11e9-8ff7-19f0aff41cef.png)
