### ISSUE TITLE
File extension may be in capital letters

### ISSUE THREAD

**Issue by dan1-ru** [singnet/dnn-model-services#58]
##### **Brief description**

When I try to invoke call with video URL, ending with capitalized letters, button "Invoke" isn't active.

##### **Screenshot**

![image](https://user-images.githubusercontent.com/7466036/53986860-1c00b980-4141-11e9-9618-08d94eea2c52.png)

Video URL: http://dev.exiv2.org/attachments/361/MAH01585.MP4

##### **Suggest a Fix**

Add ignore case on validation

##### **Version(s)**

Main Ethereum Network

##### **Browsers and Operating System**

Ubuntu 18.04, Chromium

**Comment by arturgontijo** [comment]
Fixed.
Service now also accepts youtube links: [i3d-video-action-recognition](https://beta.singularitynet.io/servicedetails/org/snet/service/i3d-video-action-recognition)
