### ISSUE TITLE
yolo3 service API contains Protobuf/JSON mixed

### ISSUE THREAD

**Issue by vsbogd** [singnet/dnn-model-services#62]
When I have tried to write yolo3 service client using Python SDK I have found that service API contains string fields which in turn contains JSON arrays with values. Such API is not self descriptive and requires using two different serialization formats (Protobuf and JSON) to write a client. 

For example in `Output` message below: https://github.com/singnet/dnn-model-services/blob/1e6faa53c06153d538671f2a81664b1f010d858f/services/yolov3-object-detection/service/service_spec/object_detection.proto#L9-L15
field `class_id` is in fact not string but JSON array represented as string.

I would propose make API composed of pure Protobuf and review other services to eliminate mixed JSON/Protobuf APIs.

**Comment by arturgontijo** [comment]
Hey @vsbogd, thanks for this.
Will update it and check other services as well.

**Comment by arturgontijo** [comment]
@vsbogd sorry for the huge delay.
Could you please review #65?

**Comment by vsbogd** [comment]
Hi @arturgontijo , sure, will review it
